org: nban22
app: todo-serverless
service: todo-serverless

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    TODOS_TABLE: ${self:service}-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt TodosTable.Arn
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

plugins:
  - serverless-offline

functions:
  create:
    handler: src/handlers/create.handler
    events:
      - http:
          path: todos
          method: post
          cors: true
  list:
    handler: src/handlers/list.handler
    events:
      - http:
          path: todos
          method: get
          cors: true
  get:
    handler: src/handlers/get.handler
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
  update:
    handler: src/handlers/update.handler
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
  delete:
    handler: src/handlers/delete.handler
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH